#!/bin/env -S bash --noprofile --norc

set -euo pipefail

export DIR='WorkDir'
export PATHPAT='/home/'

echo "Active (Running) Jobs:"

scontrol show job \
	| awk -v RS= -v ORS="\n\n" -v dir="$DIR" -v path="$PATHPAT" '$0 ~ (dir "=" path) && match($0, /RunTime=([0-9:-]+)/, a) && a[1] != "00:00:00"' \
	| grep -P "UserId=|RunTime=|$DIR=$PATHPAT" \
	| grep -B 2 "$DIR=$PATHPAT" \
	| grep "UserId" \
	| sort \
	| uniq -c \
	| sort -nr

echo "Scheduled Jobs:"

scontrol show job \
	| awk -v RS= -v ORS="\n\n" -v dir="$DIR" -v path="$PATHPAT" '$0 ~ (dir "=" path) ' \
	| grep -P "UserId=|RunTime=|$DIR=$PATHPAT" \
	| grep -B 2 "$DIR=$PATHPAT" \
	| grep "UserId" \
	| sort \
	| uniq -c \
	| sort -nr



